### ISSUE TITLE
wnd-charm Install Error

### ISSUE THREAD

**Issue by gwaybio** [rohdelab/cell-image-classification#1]
I am trying to reproduce the analysis presented here - thank you for posting it!

I am having some trouble installing `wnd-charm`. It is not playing nicely. Specifically, I am receiving this error:

```bash
checking for main in -lchrm... no
checking for fftw_execute in -lfftw3... no
configure: error: 
    FFTW3 library not found.
    Please download+install FFTW 3.x from http://www.fftw.org/download.html
```

I've tried installing 3 different versions of FFTW3 to no avail. I am wondering if you know of a quick solution.

**Comment by xuwangyin** [comment]
On our system (Ubuntu 16.04) we installed it via the package manager `apt-get install libfftw3-dev`. Please first try to install it using the system's package manager. Otherwise follow the installation guide at http://www.fftw.org/fftw3_doc/Installation-and-Customization.html.

**Comment by gwaybio** [comment]
thanks for your quick reply and thanks for your suggestion on installing `libfftw3-dev` @xuwangyin - with your suggestion combined with some additional work, I was able to install wnd-charm. There were several additional steps required, which I will outline below.

Previously, I was trying to build from source, and the `wnd-charm` install could not see `fftw_execute`. After using the `apt-get` strategy, `wnd-charm` can see `fftw3` now, so thanks for getting me over this first hurdle! 

I was able to install the command line tool `wndchrm` by running `sudo bash build.sh` after cloning the repo (https://github.com/wnd-charm/wnd-charm).

I was also able to install the python API - here are my steps.

## Setup.py with Python 3

Following instructions in the wnd-charm README:

```bash
(base) greg@lava ~/repos/cell-image-classification/wnd-charm $ python setup.py build
  File "setup.py", line 49
    print "Building WND-CHARM {} at git repo commit {}...".format( __version__, git_hash )
                                                         ^
SyntaxError: invalid syntax
```

It looks like these instructions are specific to python 2.

## Setup.py with Python 2.7.15

```bash
(wnd) greg@lava ~/repos/cell-image-classification/wnd-charm $ python setup.py build
Building WND-CHARM 0.9.14 at git repo commit 67bfe4elocalmod...
running build
running build_ext
running build_py
copying wndcharm/_git_hash.py -> build/lib.linux-x86_64-2.7/wndcharm
(wnd) greg@lava ~/repos/cell-image-classification/wnd-charm $ python
Python 2.7.15 | packaged by conda-forge | (default, Jul  2 2019, 00:39:44) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import wndcharm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "wndcharm/__init__.py", line 27, in <module>
    from wndcharm import *
  File "wndcharm/wndcharm.py", line 28, in <module>
    _wndcharm = swig_import_helper()
  File "wndcharm/wndcharm.py", line 20, in swig_import_helper
    import _wndcharm
ImportError: No module named _wndcharm
>>> 
```

However, based on wnd-charm/wnd-charm#3, it looks like running `build` twice, actually completes the install :tada: 

```bash
(wnd) greg@lava ~/repos/cell-image-classification/wnd-charm $ python setup.py build
Building WND-CHARM 0.9.14 at git repo commit 67bfe4elocalmod...
running build
running build_ext
running build_py
copying wndcharm/_git_hash.py -> build/lib.linux-x86_64-2.7/wndcharm
(wnd) greg@lava ~/repos/cell-image-classification/wnd-charm $ python
Python 2.7.15 | packaged by conda-forge | (default, Jul  2 2019, 00:39:44) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import wndcharm
>>> exit()
```

## Summary

I was able to install `wnd-charm` python API using python 2.7.15. Thanks again!
